INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Apple Watch','apple-watch-2.png','The latest generation Apple watch.',300);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Beauty','Body Care Collection','beauty-cream.png','A hand selected collection of the finest products we offer.',150);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Beauty','Feather Boa','beauty1.png','The iconic feather fashion boa.',18);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Beauty','Lipstick Holder','beauty2.png','The Lipstick Holder clips to your bag ensuring easy access whenever you need it.',11);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Beauty','Makeup Brush Selection','bgbeauty.png','A hand selected collection of our finest brushes for applying makeup or holding up to hide your face.',76);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Circle Half-Back Chair','bgchair1.png','The iconic circular button back chair.',280);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','The Square Chair','bgchair2.png','An ultra-functional chair specifically designed for extended sitting.',260);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Tipsy Stool','bgchair3.png','A mildly disconcerting stool to sit prone to tipping over.  Perfect seating option to offer our mother-in-law.',320);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','The Highback','bgchair4','Quality meets fashion in this two-piece highback chair.',230);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','The Minimalist','bgchair5.png','Light but sturdy, this chair prefers sitting keeping a comfortable distance from you and bathing in slits of light.',140);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Retro Masterpiece','bgchair6.png','Relive the uncomfortable seating of the 1960s in a chair built to survive World War 3.',89);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Earbuds','bgearphone.png','Active noise-cancelling, latest generation.',230);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Expression Headphones','bghead-phone1.png','Headphones that come in a variety of colors.',459);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Golden Headphones','bghead-phone2.png','Noise Cancelling, 24k headphones.',13990);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','16inch Laptop','bglaptop2.png','16inch Laptop. Silver.',1699);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','14inch Laptop','bglaptop3.png','14inch Laptop. Silver',1399);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','13inch Laptop','bglaptop4.png','13inch Laptop. Silver.',1199);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Compact Laptop','bglaptop5.png','Compact Laptop. Silver.',900);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Touchscreen Laptop','bglaptop6.png','Touchscreen Laptop. Silver.',1799);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Ironworks Pendant Light','bglight.png','Classic iron framed pendant light. Ships with 1x14watt equivalent LED bulb.',89);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Apple Iphone 256GB','bgmobile1.png','Latest generation Apple Iphone 256GB.',1400);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Apple Iphone Compacy 128GB','bgmobile2.png','Latest generataion compact Apple Iphone 128GB.',1100);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Retro Apple Iphone','bgmobile5.png','Iphone from what appears to be 1932 that we found in the closet when we were cleaning the office.',4500);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Indoor Planter','bgvessel.png','Indoor planter made from solid walnut designed to be placed precariously near table edges.',65);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Blu Shirt','blu-tshirt.png','All cotton printed tshirt.',16);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Home','Bonsai Tree','bonsai-tree.png','A gorgeous bonsai tree with planter.',55);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Maroni Mirrorless FH8','camera-1.png','Maroni Mirroless FH8 camera, body only.',3400);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Capshot Digital SLR Camera','camera.png','Capshot Digital SLR Camera with 17-80mm 3.4-45f Lens.',2800);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','Condiment Starter Kit','cereal.png','A hand selected collection of the finest condiments available.  Giftwrapped.  ',90);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','College Dorm Starter Kit','chair-and-clothes.png','Perfect for a new college student. Includes a pile of comfortable dorm loungewear and chair small enough to fit dorm rooms.',149);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','Custom Selected Outfit','clothes.png','Order a custom outfit selected by our fashion team for your grown child living at home who lives in sweats or partner who has worn New Balance shoes exclusively for the last 30 years.',320);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Lixit NewHeights Drone','drone.png','The latest generation Lixit drone.',1399);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Rockheart 3-complication Chronograph RH88','flash-2.png','Rockheart model 8S with depth meter, chronograph, and moon cycles.',699);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Diamondback Blue Oxford','formal-shirt.png','Custom printed Diamondback 100% wool oxford shirt.',88);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Rockheart Extreme Collection RF100','golden-watch.png','24k Gold Watch designed to make you look way, way richer than you are.',13890);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','HiClip 80 Headphones','hiclipart.com1.png','Hiclip model 80 noise cancelling headphones in black.',180);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Beauty','Flashlight Lipstick Case','imagelipstick.png','A lipstick case that includes a built-in flashlight.  Somebody thought these were a good idea.  Please buy one to keep Dan from losing his job.',14);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Watch and two rocks','imagesmart-watch.png','A watch with a black band and two rocks.  Not intended for use together.  Why do we have this?',180);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Pair of Brown Jackets','jacket.png','Brown canvas pair of jackets',220);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Pile of Jeans','jeans-pant.png','Assorted pile of jeans in a variety of colors and sizes.',240);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Kisspring Aviator Chronograph','kissinger.png','Kisspring Aviator Chronograph model KA44 in Silver.',1399);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','Make-up Travel Kit','make-up.png','Everything needed to keep your makeup fresh while traveling.  Includes a faux leather carrying case.',84);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','An untied black shoe','nike-black.png','A single shoe. Perfect if you have lost one of yours.  Comes untied to make slipping it on faster.',70);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','Gift Bag Gift Set','paper-bag.png','The perfect gift for the person who has everything.  A selection of high quality gift bags perfect for wrapping any occasion.',140);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Tech','Hardi Mirrorless LK-11 Camera','Rectangle 116.png','Hardi Mirrorless LK-11 version 2 Camera.',899);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Retro Swishy Skirt','red-dress.png','Retro dress-up costume apparel.  Size S->XL',28);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','SlimFrame Aviator Sunglasses','sunglass.png','Classic Aviator sunglasses with gold frame from SlimeFrame Apparel.',290);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Apparel','Offensive Tshirt','t-shirt4.png','100% cotton blend TriStretch t-shirt.  Hilarious but so offensive we could not show the front of it.',55);
INSERT INTO catalog (category,title,img,short_desc,price) VALUES('Gift','Waffle Making Kit','wafflekit.png','Waffle making kit with hand selected toppings including vegetables, cheeses from around the world, and bologna.',139);
