POST https://localhost:5130
Content-Type: application/json

{
    "CreateYear": 1900,
    "Email": "test@example.com",
    "InsuranceType": "test@example.com",
    "ItemDesc": "test@example.com",
    "ItemName": "test@example.com",
    "Name": "test@example.com",
    "PreviousInsurer": "your mom",
    "ItemValue": "your mom",
    "MFREF": "your mom",
    "Status": "your mom",
    "CustRef": "your mom",
    "CreateTime": "your mom",
    "UpdateTime": "your mom",
    "PolicyEstimate": "your mom",
}


    public int? CreateYear { get; set; }
    public String? Email { get; set; }
    public String? InsuranceType { get; set; }
    public String? ItemDesc { get; set; }
    public String? ItemName { get; set; }
    public String? Name { get; set; }
    public String? PreviousInsurer { get; set; }
    public decimal ItemValue { get; set; }
    public int? MFREF { get; set; }
    public String? Status { get; set; }
    public String? CustRef { get; set; }
    public DateTime? CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public decimal? PolicyEstimate { get; set; }